server:
    port: 5000
spring:
    mvc:
        locale: ru_RU
        locale-resolver: fixed
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    datasource:
        driver-class-name: org.postgresql.Driver
        username: pdtkkixjqflcah
        password: c587f7361a3c90c7a0c2e0df2ac977c6381c97de0acd7d8d059a5bf03efce269
        platform: postgres
        url: jdbc:postgresql://ec2-52-209-171-51.eu-west-1.compute.amazonaws.com:5432/dfsn5vr5hr2kht
        continue-on-error: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: POSTGRESQL
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                order_by.default_null_ordering: last
                default_schema: mctm
                jdbc:
                    lob:
                        non_contextual_creation: true
                    time_zone: UTC
        show-sql: false
    jackson:
        serialization:
            fail_on_empty_beans:
                false
localeTag: ru-RU
logging:
    level:
        root: info
    pattern:
        console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level)
            %logger.%M - %msg%n'
pingtask:
    period: 1200000
    url: https://www.google.com
telegrambot:
    botToken: 5217016298:AAHSQASr1zWnIcloMxRlT0hKU2HrHQeluvQ
#    proxyHost: localhost
#    proxyPort: 9150
#    proxyType: SOCKS5
    userName: '@MantraSharingTest_bot'
    webHookPath: https://e87b-109-252-117-185.ngrok.io

